#!/usr/bin/env bash
#
# compose.sh — emit a per-app sidecar compose fragment to stdout.
#
# Emits to stdout, not the file: /platform is ro inside dc-run.sh
# ephemerals, so the host redirect (> docker/sidecars/<app>.yml) is the
# only write path that preserves the ro invariant. The IDE-attach
# container has a narrow nested rw bind on /platform/docker/sidecars
# (compose.dev.yml) so the same redirect works from its terminal too.

set -euo pipefail

APP="${1:-}"
SIDECAR_MODE="${2:-}"

if [ -z "$APP" ] || [ -z "$SIDECAR_MODE" ]; then
	echo "Usage: compose.sh <app> <hmr|watch>" >&2
	exit 2
fi

case "$SIDECAR_MODE" in
	hmr|watch) ;;
	*)
		echo "Usage: compose.sh <app> <hmr|watch>" >&2
		exit 2
		;;
esac

# HMR config at /app/webpack.hmr.js; the `<app base> → itsl → hmr`
# require chain resolves via relative require inside the configs.
#
# Run via `npx ... -- webpack`, NOT the direct binary: most NC apps'
# webpack-vue-config reads npm_package_name/_version (entry/output
# naming) which npm/npx inject from the cwd package.json; direct exec
# skips injection and webpack crashes. `--offline --no` block any
# registry fetch/install (supply-chain-safe). WORKDIR /app (node-
# sidecar Dockerfile) is where npx finds the binary and package.json.
#
# Healthcheck TCP-probes 3000 because `make webpack MODE=hmr` runs
# regen-htaccess right after `dc up --wait`, and regen TCP-probes
# sidecar-<app>:3000 to decide HMR proxy inclusion. Without it, --wait
# returns before webpack binds 3000 (~30s to first compile) and the
# proxy block stays empty until the next transition. `node -e` probe:
# node is the only interpreter guaranteed in node:24-slim.
emit_hmr_extras() {
	cat <<'HMR'
    command:
      - "npx"
      - "--offline"
      - "--no"
      - "--"
      - "webpack"
      - "serve"
      - "--mode"
      - "development"
      - "--config"
      - "/app/webpack.hmr.js"
    healthcheck:
      test:
        - "CMD"
        - "node"
        - "-e"
        - "require('net').createConnection(3000,'127.0.0.1').once('connect',()=>process.exit(0)).once('error',()=>process.exit(1))"
      interval: 2s
      timeout: 2s
      retries: 60
      start_period: 10s
HMR
}

# watch config at /app/webpack.itsl.js — base layer, no devServer. No
# healthcheck: --watch binds no port, so there's nothing to probe;
# readiness = container running. Same npx rationale as HMR (above).
emit_watch_extras() {
	cat <<'WATCH'
    command:
      - "npx"
      - "--offline"
      - "--no"
      - "--"
      - "webpack"
      - "--watch"
      - "--mode"
      - "development"
      - "--config"
      - "/app/webpack.itsl.js"
WATCH
}

# NODE_ENV is load-bearing: upstream configs (e.g. webpack-vue-config)
# read it at require-time to gate optimization.minimize/TerserPlugin.
# webpack's --mode flag only affects DefinePlugin substitution in
# bundled code, not the Node process env — both are needed.
#
# /overlay sibling-mount: .build/'s relative symlinks (e.g. /app/src/
# itsl -> ../../overlay/src/itsl) resolve because the target evaluates
# from the symlink's dir, so 2-up from /app/<sub>/ lands at /overlay/.
# ro because webpack must never write overlay/ — the dev's
# source-of-truth, written via make quilt only.
#
# init: true — node-sidecar has no ENTRYPOINT, so compose's docker-init
# (tini) runs PID 1 to reap webpack's children and forward SIGTERM on
# stop/restart. Using compose's primitive instead of baking tini keeps
# the image at base + user-provisioning only.
emit_sidecar() {
	local app="$1" sidecar_mode="$2"
	cat <<HEADER
# Auto-generated by scripts/compose.sh — do not edit.
services:
  sidecar-${app}:
    build:
      # context "node-sidecar": compose resolves relative \`context:\`
      # against the FIRST -f file's directory (the project_directory),
      # which the Makefile \$(DC) macro sets to docker/ by listing
      # docker/compose.yml first. So this resolves to docker/node-
      # sidecar — the Dockerfile's home. The node-sidecar Dockerfile
      # is self-contained (no COPY of platform files) so the narrow
      # subdir context is sufficient.
      #
      # Note: the path is "node-sidecar" not "../node-sidecar" even
      # though THIS file lives in docker/sidecars/. Compose's path
      # resolution uses the first-loaded compose file's dir, not the
      # file containing the relative path — easy to miscount otherwise.
      context: node-sidecar
      args:
        DEVELOPER_UID: "\${DEVELOPER_UID:-1000}"
        DEVELOPER_GID: "\${DEVELOPER_GID:-1000}"
    image: "hubs-apps/node-sidecar:\${NODE_SIDECAR_VERSION:?NODE_SIDECAR_VERSION not set — invoke via make (which reads docker/node-sidecar/VERSION)}"
    container_name: sidecar-${app}
    init: true
    networks:
      - nextcloud
    restart: unless-stopped
    environment:
      NODE_ENV: development
      WEBPACK_APP_NAME: ${app}
      WEBPACK_APP_DIR: /app
      NODE_PATH: /app/node_modules
    volumes:
      # Bind sources MUST be absolute host paths — the host daemon
      # resolves them regardless of where the compose client runs
      # (host shell vs IDE-attach integrated terminal). Relative
      # paths like \`./apps/...\` resolve client-side to the compose
      # binary's cwd, which is /platform inside the container and
      # the host's project dir outside — different paths. The host
      # daemon's create_host_path:true default then silently invents
      # empty dirs at the wrong path inside the container, leaving
      # the sidecar's /app and /overlay empty (no webpack visible,
      # npx --offline crashes loudly — the only silver lining of an
      # otherwise-silent failure mode).
      # HOST_PROJECT_DIR is the same value compose interpolates for
      # docker/compose.yml's nextcloud apps bind; same mechanism.
      # \\\${} (escaped) so compose interpolates at fragment-read time,
      # not bash at fragment-write time.
      - \${HOST_PROJECT_DIR}/apps/${app}/.build:/app
      - \${HOST_PROJECT_DIR}/apps/${app}/overlay:/overlay:ro
HEADER
	case "$sidecar_mode" in
		hmr)   emit_hmr_extras ;;
		watch) emit_watch_extras ;;
	esac
}

emit_sidecar "$APP" "$SIDECAR_MODE"
