// Demo fixture data — queue-variant widgets (set B).
// Each entry is a `queue` descriptor per docs/DEMO-WIDGETS-CONTRACT.md.
// Swedish, persona-coherent, anonymised (role labels + dnr/case ids, no PII).
// Brand rule: never the words "Nextcloud" or "Talk".
// Static fixtures only — no imports, no functions, no Date.now.

export default {
	// --- Överförmyndare / HR / registrator: e-underskriftskö ("Att signera") ---
	// Kravnivå-badge SES/AES/QES (eIDAS) + laga-kraft/frist-deadline.
	attSignera: {
		variant: 'queue',
		emptyText: 'Inga dokument väntar på din underskrift',
		headerStat: { label: 'Väntar på min e-underskrift', value: '6 dokument', tone: 'warning' },
		rows: [
			{
				id: 'sig1',
				title: 'Granska & signera arvodesbeslut',
				subtitle: 'Dnr ÖF 2026-0421 · ställföreträdare GM-184 · inkom igår',
				status: { label: 'Klar för underskrift', tone: 'info' },
				deadline: { label: 'Laga kraft-frist: 9 dagar', tone: 'warning' },
				badges: [{ label: 'AES · BankID', tone: 'success', icon: 'FileSign' }],
				primaryAction: { label: 'Granska & signera' },
			},
			{
				id: 'sig2',
				title: 'Granska & signera sluträkning',
				subtitle: 'Dnr ÖF 2026-0388 · avslutat uppdrag · huvudman HM-052',
				status: { label: 'Klar för underskrift', tone: 'info' },
				deadline: { label: '2 dagar kvar', tone: 'error' },
				badges: [{ label: 'AES · BankID', tone: 'success', icon: 'FileSign' }],
				primaryAction: { label: 'Granska & signera' },
			},
			{
				id: 'sig3',
				title: 'Granska & signera tillsynsbeslut',
				subtitle: 'Dnr ÖF 2026-0410 · uttag från spärrat konto',
				status: { label: 'Väntar på min tur', tone: 'neutral' },
				deadline: { label: 'Laga kraft-frist: 14 dagar', tone: 'neutral' },
				badges: [{ label: 'AES · Freja', tone: 'success', icon: 'FileSign' }],
				primaryAction: { label: 'Granska & signera' },
			},
			{
				id: 'sig4',
				title: 'Skriv under anställningsavtal',
				subtitle: 'Personalärende PA 2026-117 · nyrekrytering · tillträde 1 aug',
				status: { label: 'Klar för underskrift', tone: 'info' },
				deadline: { label: '5 dagar kvar', tone: 'warning' },
				badges: [{ label: 'AES · BankID', tone: 'success', icon: 'FileSign' }],
				primaryAction: { label: 'Skriv under' },
			},
			{
				id: 'sig5',
				title: 'Godkänn tjänsteanteckning',
				subtitle: 'Internt lågriskbeslut · loggat godkännande räcker',
				status: { label: 'Endast godkännande', tone: 'neutral' },
				badges: [{ label: 'SES · godkänn', tone: 'info', icon: 'CheckDecagram' }],
				primaryAction: { label: 'Godkänn' },
			},
			{
				id: 'sig6',
				title: 'Granska & signera protokoll',
				subtitle: 'Nämndprotokoll SN § 44–61 · justerare 2 av 2',
				status: { label: 'Väntar på justerare', tone: 'neutral' },
				deadline: { label: 'Justeras senast: 3 dagar', tone: 'warning' },
				badges: [{ label: 'QES krävs', tone: 'warning', icon: 'ShieldCheck' }],
				primaryAction: { label: 'Granska & signera' },
			},
		],
	},

	// --- Spegelbild: utskickat för signering, per-part statuskedja + Påminn ---
	skickatForSignering: {
		variant: 'queue',
		emptyText: 'Inget utskickat väntar på motpart',
		headerStat: { label: 'Utskickat — väntar på motpart', value: '5 ärenden', tone: 'info' },
		rows: [
			{
				id: 'out1',
				title: 'Påminn — begäran om komplettering',
				subtitle: 'Dnr ÖF 2026-0356 · ställföreträdare GM-077 · saknar 2 verifikat',
				status: { label: 'Öppnat — ej besvarat', tone: 'warning' },
				deadline: { label: 'Svarsfrist: 3 dagar', tone: 'warning' },
				badges: [{ label: 'Läskvittens 18 jun', tone: 'info', icon: 'EmailCheck' }],
				channel: 'secure',
				primaryAction: { label: 'Påminn' },
			},
			{
				id: 'out2',
				title: 'Följ upp arvodesbeslut till delgivning',
				subtitle: 'Dnr ÖF 2026-0341 · delgivning till ställföreträdare',
				status: { label: 'Signerat 1 av 2', tone: 'info' },
				deadline: { label: 'Väntar på huvudman', tone: 'neutral' },
				badges: [{ label: 'AES · BankID', tone: 'success', icon: 'FileSign' }],
				channel: 'secure',
				primaryAction: { label: 'Påminn' },
			},
			{
				id: 'out3',
				title: 'Påminn — rehaböverenskommelse',
				subtitle: 'Personalärende PA 2026-091 · medarbetare via säker länk',
				status: { label: 'Skickat — ej öppnat', tone: 'neutral' },
				deadline: { label: '4 dagar utan svar', tone: 'warning' },
				badges: [{ label: 'Säker kanal', tone: 'info', icon: 'ShieldLock' }],
				channel: 'secure',
				primaryAction: { label: 'Påminn' },
			},
			{
				id: 'out4',
				title: 'Bevaka besked till bank (SDK)',
				subtitle: 'Dnr ÖF 2026-0399 · uttag spärrat konto · org-till-org',
				status: { label: 'Levererat — kvittens väntar', tone: 'info' },
				deadline: { label: 'Inom frist', tone: 'success' },
				badges: [{ label: 'Leveranskvittens', tone: 'success', icon: 'EmailCheck' }],
				channel: 'sdk',
				primaryAction: { label: 'Visa kvittens' },
			},
			{
				id: 'out5',
				title: 'Hantera utgånget — anställningsavtal',
				subtitle: 'Personalärende PA 2026-088 · signeringslänk gick ut',
				status: { label: 'Utgånget', tone: 'error' },
				deadline: { label: 'Skicka om', tone: 'error' },
				badges: [{ label: 'AES · BankID', tone: 'success', icon: 'FileSign' }],
				channel: 'secure',
				primaryAction: { label: 'Skicka om' },
			},
		],
	},

	// --- Förvaltare/CISO: incidentrapporter med MCF-nedräkningsklockor 24h/72h/1mån ---
	incidentrapporter: {
		variant: 'queue',
		emptyText: 'Inga öppna incidenter — inga frister till MCF',
		headerStat: { label: 'Öppna incidenter · MCF-frister', value: '2 aktiva · 0 missade', tone: 'warning' },
		rows: [
			{
				id: 'inc1',
				title: 'Skicka tidig varning till MCF',
				subtitle: 'INC 2026-014 · misslyckade inloggningar mot funktionsadress',
				status: { label: 'Eskalerad till incident', tone: 'error' },
				deadline: { label: 'Tidig varning: 18 h 40 min kvar', tone: 'error' },
				badges: [{ label: '24 h-klocka', tone: 'error', icon: 'ClockAlert' }],
				primaryAction: { label: 'Skicka tidig varning' },
			},
			{
				id: 'inc2',
				title: 'Komplettera incidentanmälan till MCF',
				subtitle: 'INC 2026-012 · avvikande delning utanför organisationen',
				status: { label: 'Tidig varning skickad', tone: 'warning' },
				deadline: { label: 'Incidentanmälan: 1 dag 6 h kvar', tone: 'warning' },
				badges: [{ label: '72 h-klocka', tone: 'warning', icon: 'ClockAlert' }],
				primaryAction: { label: 'Komplettera anmälan' },
			},
			{
				id: 'inc3',
				title: 'Lämna lägesrapport till MCF',
				subtitle: 'INC 2026-009 · pågående · accesspunktstörning utredd',
				status: { label: 'Anmälan inlämnad', tone: 'info' },
				deadline: { label: 'Lägesrapport: 12 dagar kvar', tone: 'neutral' },
				badges: [{ label: '1 mån-klocka', tone: 'neutral', icon: 'ClockOutline' }],
				primaryAction: { label: 'Skapa lägesrapport' },
			},
			{
				id: 'inc4',
				title: 'Färdigställ slutrapport till MCF',
				subtitle: 'INC 2026-006 · avslutad · trolig orsak fastställd',
				status: { label: 'Åtgärdad', tone: 'success' },
				deadline: { label: 'Slutrapport: 21 dagar kvar', tone: 'neutral' },
				badges: [{ label: 'Slutrapport', tone: 'info', icon: 'FileDocumentCheck' }],
				primaryAction: { label: 'Färdigställ slutrapport' },
			},
		],
	},

	// --- Förvaltare/CISO: säkerhetshändelse-feed, Eskalera-knapp förfyller incident ---
	sakerhetshandelser: {
		variant: 'queue',
		emptyText: 'Inga öppna säkerhetshändelser',
		headerStat: { label: 'Öppna säkerhetshändelser', value: '5 att bedöma', tone: 'warning' },
		rows: [
			{
				id: 'sec1',
				title: 'Eskalera till incident',
				subtitle: '34 misslyckade inloggningar · funktionsadress orosanmalan@ · 10 min',
				status: { label: 'Avvikelse', tone: 'error' },
				deadline: { label: 'Bedöm skyndsamt', tone: 'error' },
				badges: [{ label: 'Auth-spik', tone: 'error', icon: 'AccountAlert' }],
				primaryAction: { label: 'Eskalera till incident' },
			},
			{
				id: 'sec2',
				title: 'Eskalera till incident',
				subtitle: 'Delning till extern mottagare utanför grupp · ärenderum SN 2026-0142',
				status: { label: 'Avvikande delning', tone: 'warning' },
				deadline: { label: 'Granska idag', tone: 'warning' },
				badges: [{ label: 'Utomgruppsdelning', tone: 'warning', icon: 'AccountShare' }],
				primaryAction: { label: 'Eskalera till incident' },
			},
			{
				id: 'sec3',
				title: 'Bedöm avvikelse',
				subtitle: 'Inloggning under tröskel-LOA (LOA2) mot känsligt flöde',
				status: { label: 'Under tröskel', tone: 'warning' },
				deadline: { label: 'Granska idag', tone: 'warning' },
				badges: [{ label: 'LOA2 < krav', tone: 'warning', icon: 'ShieldAlert' }],
				primaryAction: { label: 'Visa session' },
			},
			{
				id: 'sec4',
				title: 'Bedöm avvikelse',
				subtitle: 'Meddelande sänt till oväntad funktionsadress · möjligt felskick',
				status: { label: 'Att granska', tone: 'info' },
				deadline: { label: 'Inom dygnet', tone: 'neutral' },
				badges: [{ label: 'Fel mottagare?', tone: 'info', icon: 'EmailAlert' }],
				primaryAction: { label: 'Visa routing' },
			},
			{
				id: 'sec5',
				title: 'Kvittera hanterad händelse',
				subtitle: 'Upprepade nekade åtkomstförsök mot ärenderum · spärrad',
				status: { label: 'Åtgärdad', tone: 'success' },
				badges: [{ label: 'Loggad', tone: 'success', icon: 'ShieldCheck' }],
				primaryAction: { label: 'Kvittera' },
			},
		],
	},

	// --- Registrator: registrera & fördela, förifylld diarieföring ---
	registreraFordela: {
		variant: 'queue',
		emptyText: 'Inget oregistrerat — allt är diariefört',
		headerStat: { label: 'Oregistrerat · frist idag', value: '6 oregistrerade · 2 frist idag', tone: 'warning' },
		rows: [
			{
				id: 'reg1',
				title: 'Registrera & fördela handling',
				subtitle: 'Förslag dnr KS 2026-0902 · avsändare verifierad · inkom idag 07:14',
				status: { label: 'Ny — oregistrerad', tone: 'info' },
				deadline: { label: 'Registreras senast nästa arbetsdag', tone: 'warning' },
				badges: [{ label: 'Förifylld registrering', tone: 'success', icon: 'FileDocumentEdit' }],
				channel: 'sdk',
				primaryAction: { label: 'Registrera & fördela' },
			},
			{
				id: 'reg2',
				title: 'Registrera & fördela handling',
				subtitle: 'Förslag dnr SN 2026-0143 · ärendemening föreslagen · sekretessmarkering?',
				status: { label: 'Ny — oregistrerad', tone: 'info' },
				deadline: { label: 'Frist idag', tone: 'error' },
				badges: [{ label: 'Möjlig sekretess (OSL)', tone: 'warning', icon: 'ShieldLock' }],
				channel: 'secure',
				primaryAction: { label: 'Registrera & fördela' },
			},
			{
				id: 'reg3',
				title: 'Registrera & fördela handling',
				subtitle: 'Förslag dnr BN 2026-0457 · remissvar · massregistrering möjlig',
				status: { label: 'Påbörjad', tone: 'neutral' },
				deadline: { label: 'Frist idag', tone: 'error' },
				badges: [{ label: 'Likartad — batch', tone: 'info', icon: 'FileMultiple' }],
				channel: 'internal',
				primaryAction: { label: 'Registrera & fördela' },
			},
			{
				id: 'reg4',
				title: 'Registrera fax-in & fördela',
				subtitle: 'Inskannad fax · avsändare okänd · komplettera avsändare',
				status: { label: 'Åtgärd krävs', tone: 'warning' },
				deadline: { label: 'Registreras senast nästa arbetsdag', tone: 'warning' },
				badges: [{ label: 'Migreringsbrygga', tone: 'neutral', icon: 'Fax' }],
				channel: 'fax',
				primaryAction: { label: 'Registrera & fördela' },
			},
			{
				id: 'reg5',
				title: 'Omfördela felskickad handling',
				subtitle: 'Inkom till fel funktionsadress · ärendemening klar',
				status: { label: 'Att omfördela', tone: 'warning' },
				badges: [{ label: 'Fel funktionsadress', tone: 'warning', icon: 'EmailAlert' }],
				channel: 'secure',
				primaryAction: { label: 'Fördela om' },
			},
			{
				id: 'reg6',
				title: 'Registrera & fördela e-tjänsteärende',
				subtitle: 'Förslag dnr KS 2026-0903 · komplett underlag · tilldela handläggare',
				status: { label: 'Ny — oregistrerad', tone: 'info' },
				deadline: { label: 'Registreras senast nästa arbetsdag', tone: 'neutral' },
				badges: [{ label: 'Förifylld registrering', tone: 'success', icon: 'FileDocumentEdit' }],
				channel: 'internal',
				primaryAction: { label: 'Registrera & fördela' },
			},
		],
	},

	// --- Registrator: utlämnande av allmän handling, sekretessprövning + skyndsamt-timer ---
	utlamnande: {
		variant: 'queue',
		emptyText: 'Inga öppna utlämnandeframställningar',
		headerStat: { label: 'Framställningar · skyndsamt', value: '4 öppna', tone: 'warning' },
		rows: [
			{
				id: 'ut1',
				title: 'Gör sekretessprövning & lämna ut',
				subtitle: 'Dnr KS 2026-0871 · begäran från journalist · 6 handlingar',
				status: { label: 'Sekretessprövning pågår', tone: 'warning' },
				deadline: { label: 'Skyndsamt: inkom igår', tone: 'error' },
				badges: [{ label: 'Maskering krävs', tone: 'warning', icon: 'ShieldLock' }],
				channel: 'secure',
				primaryAction: { label: 'Pröva & lämna ut' },
			},
			{
				id: 'ut2',
				title: 'Lämna ut allmän handling',
				subtitle: 'Dnr SN 2026-0120 · begäran från ombud · prövning klar',
				status: { label: 'Klar att skicka', tone: 'info' },
				deadline: { label: 'Skyndsamt: idag', tone: 'warning' },
				badges: [{ label: 'Utlämnande loggas', tone: 'info', icon: 'FileDocumentCheck' }],
				channel: 'secure',
				primaryAction: { label: 'Skicka säkert' },
			},
			{
				id: 'ut3',
				title: 'Sök & identifiera handlingar',
				subtitle: 'Dnr BN 2026-0402 · begäran från privatperson · diariesök',
				status: { label: 'Ny framställan', tone: 'info' },
				deadline: { label: 'Skyndsamt: inkom idag', tone: 'warning' },
				badges: [{ label: 'Diariesök', tone: 'neutral', icon: 'FileSearch' }],
				primaryAction: { label: 'Sök i diariet' },
			},
			{
				id: 'ut4',
				title: 'Pröva avslag & motivera',
				subtitle: 'Dnr KS 2026-0860 · begärd handling helt sekretessbelagd',
				status: { label: 'Åtgärd krävs', tone: 'warning' },
				deadline: { label: 'Beslut med besvärshänvisning', tone: 'neutral' },
				badges: [{ label: 'Sekretess OSL', tone: 'warning', icon: 'ShieldLock' }],
				primaryAction: { label: 'Skriv beslut' },
			},
		],
	},

	// --- Överförmyndare: uppdragskontroll, flaggade ställföreträdare (JO-kravet) ---
	uppdragskontroll: {
		variant: 'queue',
		emptyText: 'Inga ställföreträdare flaggade för fördjupad tillsyn',
		headerStat: { label: 'Flaggade för fördjupad tillsyn', value: '4 ställföreträdare', tone: 'warning' },
		rows: [
			{
				id: 'upp1',
				title: 'Granska uppdragsmängd',
				subtitle: 'Ställföreträdare GM-204 · 11 aktiva uppdrag · över tröskel',
				status: { label: 'Ovanligt många uppdrag', tone: 'warning' },
				deadline: { label: 'Stickprov denna månad', tone: 'warning' },
				badges: [{ label: 'JO-kontroll', tone: 'warning', icon: 'AccountAlert' }],
				primaryAction: { label: 'Öppna tillsyn' },
			},
			{
				id: 'upp2',
				title: 'Granska upprepade anmärkningar',
				subtitle: 'Ställföreträdare FÖ-058 · 3 anmärkningar senaste 2 åren',
				status: { label: 'Upprepade anmärkningar', tone: 'error' },
				deadline: { label: 'Fördjupad granskning', tone: 'error' },
				badges: [{ label: 'Mönster', tone: 'error', icon: 'AlertCircle' }],
				primaryAction: { label: 'Öppna tillsyn' },
			},
			{
				id: 'upp3',
				title: 'Bedöm lämplighet — ny matchning',
				subtitle: 'Kandidat GM-204 redan flaggad · nytt godmanskap i samförstånd',
				status: { label: 'Kontroll före beslut', tone: 'warning' },
				deadline: { label: 'Inför beslut', tone: 'neutral' },
				badges: [{ label: 'Uppdragsöverblick', tone: 'info', icon: 'AccountSearch' }],
				primaryAction: { label: 'Visa uppdrag' },
			},
			{
				id: 'upp4',
				title: 'Granska försenade redovisningar',
				subtitle: 'Ställföreträdare GM-141 · 2 årsräkningar sent inkomna',
				status: { label: 'Att bevaka', tone: 'neutral' },
				deadline: { label: 'Inför nästa 1 mars', tone: 'neutral' },
				badges: [{ label: 'Förtur nästa år', tone: 'info', icon: 'FlagOutline' }],
				primaryAction: { label: 'Öppna tillsyn' },
			},
		],
	},

	// --- Registrator/nämndsekreterare: justering & anslag, laga-kraft-nedräkning ---
	justeringAnslag: {
		variant: 'queue',
		emptyText: 'Inga protokoll väntar på justering',
		headerStat: { label: 'Justering & aktiva anslag', value: '2 att justera · 3 anslag', tone: 'info' },
		rows: [
			{
				id: 'jus1',
				title: 'Justera protokoll digitalt',
				subtitle: 'Socialnämnden § 44–61 · ordförande + justerare med BankID',
				status: { label: 'Väntar på justering', tone: 'warning' },
				deadline: { label: 'Justeras senast: 2 dagar', tone: 'error' },
				badges: [{ label: 'AES · BankID', tone: 'success', icon: 'FileSign' }],
				primaryAction: { label: 'Justera & anslå' },
			},
			{
				id: 'jus2',
				title: 'Justera protokoll digitalt',
				subtitle: 'Kommunstyrelsen § 88–102 · justerare 1 av 2 klar',
				status: { label: 'Signerat 1 av 2', tone: 'info' },
				deadline: { label: 'Justeras senast: 4 dagar', tone: 'warning' },
				badges: [{ label: 'AES · BankID', tone: 'success', icon: 'FileSign' }],
				primaryAction: { label: 'Påminn justerare' },
			},
			{
				id: 'jus3',
				title: 'Bevaka anslag — laga kraft',
				subtitle: 'Byggnadsnämnden § 30 · anslaget 28 maj',
				status: { label: 'Anslag aktivt', tone: 'info' },
				deadline: { label: 'Laga kraft om: 4 dagar', tone: 'warning' },
				badges: [{ label: 'Överklagandetid', tone: 'info', icon: 'GavelOutline' }],
				primaryAction: { label: 'Visa anslag' },
			},
			{
				id: 'jus4',
				title: 'Expediera vid laga kraft',
				subtitle: 'Kommunstyrelsen § 76 · anslaget 23 maj · ingen överklagan',
				status: { label: 'Laga kraft idag', tone: 'success' },
				deadline: { label: 'Expediera & delge', tone: 'warning' },
				badges: [{ label: 'Delgivningskvittens', tone: 'success', icon: 'EmailCheck' }],
				primaryAction: { label: 'Expediera & delge' },
			},
			{
				id: 'jus5',
				title: 'Bevaka anslag — laga kraft',
				subtitle: 'Socialnämnden § 39 · anslaget 6 jun · överklagan inkommen',
				status: { label: 'Överklagan inkommen', tone: 'warning' },
				deadline: { label: 'Vidarebefordra till instans', tone: 'neutral' },
				badges: [{ label: 'Ej laga kraft', tone: 'warning', icon: 'GavelOutline' }],
				primaryAction: { label: 'Hantera överklagan' },
			},
		],
	},

	// --- HR/chef: mallar & samtycke, mallbibliotek (samtycke / plan för återgång) ---
	mallarSamtycke: {
		variant: 'queue',
		emptyText: 'Inga mallar att starta',
		headerStat: { label: 'Mallbibliotek · säker kanal', value: '6 snabbstarter', tone: 'info' },
		rows: [
			{
				id: 'mal1',
				title: 'Starta — Samtycke vårdgivarkontakt',
				subtitle: 'Säkert formulär + BankID · ersätter samtycke per post',
				status: { label: 'Mall klar', tone: 'info' },
				badges: [{ label: 'BankID-signeras', tone: 'success', icon: 'FileSign' }],
				channel: 'secure',
				primaryAction: { label: 'Skicka samtycke' },
			},
			{
				id: 'mal2',
				title: 'Starta — Plan för återgång i arbete',
				subtitle: 'FK 7459 · upprättas senast dag 30 · samredigeras med chef',
				status: { label: 'Mall klar', tone: 'info' },
				deadline: { label: 'Dag 30-tröskel', tone: 'warning' },
				badges: [{ label: 'Plan för återgång', tone: 'info', icon: 'FileDocumentEdit' }],
				primaryAction: { label: 'Starta plan' },
			},
			{
				id: 'mal3',
				title: 'Starta — Rehaböverenskommelse',
				subtitle: 'Överenskommelse om arbetsanpassning · delges medarbetare',
				status: { label: 'Mall klar', tone: 'info' },
				badges: [{ label: 'AES · BankID', tone: 'success', icon: 'FileSign' }],
				channel: 'secure',
				primaryAction: { label: 'Starta överenskommelse' },
			},
			{
				id: 'mal4',
				title: 'Starta — Kallelse till avstämningsmöte',
				subtitle: 'Medarbetare + företagshälsovård + Försäkringskassan',
				status: { label: 'Mall klar', tone: 'info' },
				badges: [{ label: 'Säkert möte', tone: 'info', icon: 'CalendarClock' }],
				channel: 'secure',
				primaryAction: { label: 'Skapa kallelse' },
			},
			{
				id: 'mal5',
				title: 'Starta — Begäran om läkarintygsförlängning',
				subtitle: 'Intyg går ut om 3 dagar · begär uppföljning',
				status: { label: 'Mall klar', tone: 'info' },
				deadline: { label: 'Intyg går ut: 3 dagar', tone: 'warning' },
				badges: [{ label: 'Uppföljning', tone: 'info', icon: 'FileClock' }],
				channel: 'secure',
				primaryAction: { label: 'Begär förlängning' },
			},
			{
				id: 'mal6',
				title: 'Starta — Anställningsavtal',
				subtitle: 'Mall i säker dokumentyta · e-underskrift på distans',
				status: { label: 'Mall klar', tone: 'info' },
				badges: [{ label: 'AES · BankID', tone: 'success', icon: 'FileSign' }],
				primaryAction: { label: 'Starta avtal' },
			},
		],
	},
}
