# .gitlab/secret-detection-ruleset.toml

# Rule to detect sdkmc_secret_password
[[rules]]
id = "sdkmc_secret_password"
description = "Detects sdkmc_secret_password variable assignments with specific criteria"
regex = '''sdkmc_secret_password\s*[:= ]\s*["']?[${][A-Za-z0-9+/=]{7,}["']?'''
#allowed_names = ["my_custom_secret_allowed"]
#allowlist = ["VAULT_SECRET_KEY"]

# Rule to detect sdkmcmwSecretPassword
[[rules]]
id = "sdkmcmwSecretPassword"
description = "Detects sdkmcmwSecretPassword in configuration files"
regex = '''(?<!\$\{?|\{\{)sdkmcmwSecretPassword\s*[:= ]\s*["']?[${][A-Za-z0-9+/=]{7,}["']?'''

# Rule to detect SdkMcMw__MessageService__ClientCertificatePassword
[[rules]]
id = "SdkMcMw__MessageService__ClientCertificatePassword"
description = "Detects SdkMcMw__MessageService__ClientCertificatePassword in configuration files"
regex = '''(?<!\$\{?|\{\{)SdkMcMw__MessageService__ClientCertificatePassword\s*[:= ]\s*["']?[${][A-Za-z0-9+/=]{7,}["']?'''

# Rule to detect SdkMcMw__MessageService__ApiBaseUri
[[rules]]
id = "SdkMcMw__MessageService__ApiBaseUri"
description = "Detects SdkMcMw__MessageService__ApiBaseUri in configuration files"
regex = '''(?<!\$\{?|\{\{)SdkMcMw__MessageService__ApiBaseUri\s*[:= ]\s*["']?[${]https?://[^\s"']+["']?'''

# Rule to detect SdkMcMw__AddressBook__ManagedOrganizationId
[[rules]]
id = "SdkMcMw__AddressBook__ManagedOrganizationId"
description = "Detects SdkMcMw__AddressBook__ManagedOrganizationId in configuration files"
regex = '''(?<!\$\{?|\{\{)SdkMcMw__AddressBook__ManagedOrganizationId\s*[:= ]\s*["']?[${][A-Za-z0-9-]{7,}["']?'''

# Rule to detect SdkMcMw__MessageClient__SecretPassword
[[rules]]
id = "SdkMcMw__MessageClient__SecretPassword"
description = "Detects SdkMcMw__MessageClient__SecretPassword in configuration files"
regex = '''(?<!\$\{?|\{\{)SdkMcMw__MessageClient__SecretPassword\s*[:= ]\s*["']?[${][A-Za-z0-9+/=]{7,}["']?'''

# Rule to detect SdkMcMw__SecretPassword
[[rules]]
id = "SdkMcMw__SecretPassword"
description = "Detects SdkMcMw__SecretPassword in configuration files"
regex = '''(?<!\$\{?|\{\{)SdkMcMw__SecretPassword\s*[:= ]\s*["']?[${][A-Za-z0-9+/=]{7,}["']?'''

# Rule to detect SSH private keys (RSA, DSA, ED25519)
[[rules]]
id = "ssh_private_key"
description = "Detects SSH private keys (RSA, DSA, ED25519)"
regex = '''(?i)(ssh-(rsa|dss|ed25519)\s+[A-Za-z0-9+/=]+\s+[^\s@]+)'''

# Rule to detect SSH private key headers and footers
[[rules]]
id = "ssh_private_key_header"
description = "Detects SSH private key headers and footers"
regex = '''(?i)(-----BEGIN (RSA|DSA|ED25519) PRIVATE KEY-----|-----END (RSA|DSA|ED25519) PRIVATE KEY-----)'''
